---
- hosts: all
  become: true
  tasks:

    # - name: Add the Jenkins GPG key
    #   apt_key:
    #     url:  https://pkg.jenkins.io/debian/jenkins.io-2023.key
    #     state: present

    - name: Install the Jenkins GPG key
      shell: |
        curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key | sudo tee \
          /usr/share/keyrings/jenkins-keyring.asc > /dev/null
          
    - name: Add the Jenkins repository
      shell: |
        echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] \
          https://pkg.jenkins.io/debian-stable binary/ | sudo tee \
          /etc/apt/sources.list.d/jenkins.list > /dev/null
          
    - name: Create the Jenkins apt repository file
      file:
        path: /etc/apt/sources.list.d/jenkins.list
        state: touch

    # - name: Add the Jenkins apt repository
    #   lineinfile:
    #     path: /etc/apt/sources.list.d/jenkins.list
    #     line: deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian binary/
    #     state: present

    - name: Add the Jenkins keyring
      apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        state: present

    - name: Update the apt cache
      apt:
        update_cache: yes

    - name: Install Java
      apt:
        name: openjdk-17-jre
        state: present

    - name: Add the Jenkins repository
      apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] \
          https://pkg.jenkins.io/debian-stable binary/
        state: present

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: "Read a file content"
      shell: |
        cat /var/lib/jenkins/secrets/initialAdminPassword
      register: file_content

    - name: "Print the file content to a console"
      debug:
        msg: "{{ file_content.stdout }}"

    - name: "Save the file content to a '$resolve_conf' variable"
      set_fact:
        resolve_conf: "{{ file_content.stdout }}"

    - name: "Print the '$resolve_conf' variable"
      debug:
        msg: "{{ resolve_conf }}"





    # - name: Add the Jenkins keyring with get_url module
    #   get_url:
    #     url: https://pkg.jenkins.io/debian/jenkins.io-2023.key
    #     dest: /usr/share/keyrings/jenkins-keyring.asc
  
    # - name: Add the Jenkins keyring with shell module
    #   shell: "curl -fsSL https://pkg.jenkins.io/debian/jenkins.io-2023.key | sudo tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null"

    # - name: Add the Jenkins repository
    #   lineinfile:
    #     path: /etc/apt/sources.list.d/jenkins.list
    #     line: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian binary/"
    #     state: present

    # - name: Update the package index
    #   apt:
    #     update_cache: yes

    # - name: Install Jenkins
    #   apt:
    #     name: jenkins
    #     state: present
